"""
Este archivo contiene listas y diccionarios que se usan para renombrar atributos
y registros del conjunto de datos, mediante un proceso de ETL
"""

cols_filter = ["STATENAME", "COUNTY",	"CITY",
               "PEDS", "PERNOTMVIT", "VE_TOTAL",
               "VE_FORMS", "PVH_INVL", "PERSONS", "PERMVIT",
               "MONTHNAME", "DAY",
               "DAY_WEEKNAME", "YEAR", "HOUR", "ROUTENAME",
               "LATITUDE", "LONGITUD",
               "LGT_CONDNAME", "WEATHERNAME", "FATALS"]

state_name = {  1: 'Alabama',
                2: 'Alaska',
                4: 'Arizona',
                5: 'Arkansas',
                6: 'California',
                8: 'Colorado',
                9: 'Connecticut',
                10: 'Delaware',
                11: 'District of Columbia',
                12: 'Florida',
                13: 'Georgia',
                15: 'Hawaii',
                16: 'Idaho',
                17: 'Illinois',
                18: 'Indiana',
                19: 'Iowa',
                20: 'Kansas',
                21: 'Kentucky',
                22: 'Louisiana',
                23: 'Maine',
                24: 'Maryland',
                25: 'Massachusetts',
                26: 'Michigan',
                27: 'Minnesota',
                28: 'Mississippi',
                29: 'Missouri',
                30: 'Montana',
                31: 'Nebraska',
                32: 'Nevada',
                33: 'New Hampshire',
                34: 'New Jersey',
                35: 'New Mexico',
                36: 'New York',
                37: 'North Carolina',
                38: 'North Dakota',
                39: 'Ohio',
                40: 'Oklahoma',
                41: 'Oregon',
                42: 'Pennsylvania',
                44: 'Rhode Island',
                45: 'South Carolina',
                46: 'South Dakota',
                47: 'Tennessee',
                48: 'Texas',
                49: 'Utah',
                50: 'Vermont',
                51: 'Virginia',
                53: 'Washington',
                54: 'West Virginia',
                55: 'Wisconsin',
                56: 'Wyoming'}


code_state = {  'Alabama': 'AL',
                'Alaska': 'AK',
                'Arizona': 'AZ',
                'Arkansas': 'AR',
                'California': 'CA',
                'Colorado': 'CO',
                'Connecticut': 'CT',
                'Delaware': 'DE',
                'District of Columbia': 'DC',
                'Florida': 'FL',
                'Georgia': 'GA',
                'Hawaii': 'HI',
                'Idaho': 'ID',
                'Illinois': 'IL',
                'Indiana': 'IN',
                'Iowa': 'IA',
                'Kansas': 'KS',
                'Kentucky': 'KY',
                'Louisiana': 'LA',
                'Maine': 'ME',
                'Maryland': 'MD',
                'Massachusetts': 'MA',
                'Michigan': 'MI',
                'Minnesota': 'MN',
                'Mississippi': 'MS',
                'Missouri': 'MO',
                'Montana': 'MT',
                'Nebraska': 'NE',
                'Nevada': 'NV',
                'New Hampshire': 'NH',
                'New Jersey': 'NJ',
                'New Mexico': 'NM',
                'New York': 'NY',
                'North Carolina': 'NC',
                'North Dakota': 'ND',
                'Ohio': 'OH',
                'Oklahoma': 'OK',
                'Oregon': 'OR',
                'Pennsylvania': 'PA',
                'Rhode Island': 'RI',
                'South Carolina': 'SC',
                'South Dakota': 'SD',
                'Tennessee': 'TN',
                'Texas': 'TX',
                'Utah': 'UT',
                'Vermont': 'VT',
                'Virginia': 'VA',
                'Washington': 'WA',
                'West Virginia': 'WV',
                'Wisconsin': 'WI',
                'Wyoming': 'WY'}

dayweek_name = { 5: 'Thursday',
                 1: 'Sunday',
                 4: 'Wednesday',
                 7: 'Saturday',
                 3: 'Tuesday',
                 2: 'Monday',
                 6: 'Friday'}

month_name = { 1: 'January',
               2: 'February',
               3: 'March',
               4: 'April',
               5: 'May',
               6: 'June',
               7: 'July',
               8: 'August',
               9: 'September',
               10: 'October',
               11: 'November',
               12: 'December'}

weather = dict(zip([1, 2, 3, 4, 5, 6, 7, 8, 10, 11, 12, 98, 99],
                   ["Clear", "Rain", "Sleet or Hail", "Snow", "Fog, Smog, Smoke", 
                    "Severe Crosswinds", "Blowing Sand, Soil, Dirt", "Other", "Cloudy", 
                    "Blowing Snow", "Freezing Rain or Drizzle", "Not Reported", "Reported as Unknown"]))


lgt_cond = dict(zip([1, 2, 3, 4, 5, 6, 7, 8, 9],
                    ["Daylight", "Dark – Not Lighted", "Dark – Lighted", "Dawn", "Dusk", 
                     "Dark – Unknown Lighting", "Other", "Not Reported", "Reported as Unknown"]))


route = dict(zip([1, 2, 3, 4, 5, 6, 7, 8, 9],
                 ["Interstate", "U.S. Highway", "State Highway", "County Road", 
                  "Local Street – Township", "Local Street – Municipality", 
                  "Local Street – Frontage Road", "Other", "Unknown"]))

change_name = {
            'statename': 'State',
            've_total': 'Total vehicles involved',
            've_forms': 'Vehicles in motion',
            'pvh_invl': 'Parked vehicles',
            'peds': 'Pedestrian',
            'permvit': 'Persons in Vehicles',
            'pernotmvit': 'Cyclists',
            'county': 'County',
            'city': 'City',
            'day': 'Day of month',
            'monthname': 'Month',
            'year': 'Year',
            'day_weekname': 'Day of week',
            'hour': 'Hour',
            'routename': 'Route',
            'lgt_condname': 'Ligth condition',
            'weathername': 'Climatic condition',
            'fatals': 'Fatals'
            }